# Generated by Django 2.2 on 2019-04-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_moroso_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moroso',
            name='date',
            field=models.DateTimeField(max_length=255),
        ),
    ]
