# Generated by Django 2.2 on 2019-04-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190430_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moroso',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
