# Generated by Django 2.2 on 2019-04-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190430_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moroso',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
