# Generated by Django 2.2 on 2019-04-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20190430_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moroso',
            name='no_apto',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='moroso',
            name='status',
            field=models.BooleanField(),
        ),
    ]
