# Generated by Django 2.2 on 2019-05-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20190430_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moroso',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
